apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "report-consumer.fullname" . }}
  labels:
    {{- include "report-consumer.labels" . | nindent 4 }}
data:
  NATS_URL: {{ .Values.env.natsUrl | quote }}
  NATS_STREAM: {{ .Values.env.natsStream | quote }}
  NATS_CONSUMER: {{ .Values.env.natsConsumer | quote }}
  NATS_CONSUME_SUBJECT: {{ .Values.env.natsConsumeSubject | quote }}
  POSTGRES_HOST: {{ .Values.env.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.env.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.env.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.env.postgresUser | quote }}
  POSTGRES_SSLMODE: {{ .Values.env.postgresSslMode | quote }}
