replicaCount: 1

image:
  repository: docker.redpanda.com/redpandadata/connect
  tag: "v4.44.1"
  pullPolicy: IfNotPresent

env:
  natsUrl: "nats://nats:4222"
  natsStream: "REPORTS"
  natsConsumer: "llm-response-connector-writer"
  natsConsumeSubject: "reports.llm.>"
  postgresHost: "postgres-postgresql"
  postgresPort: "5432"
  postgresDb: "geometrics"
  postgresUser: "geometrics"
  postgresSslMode: "disable"
  postgresAuthSecretName: "postgres-auth"
  postgresAuthPasswordKey: "password"

connector:
  logLevel: "INFO"
  shutdownTimeout: "20s"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
