apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "translation-worker.fullname" . }}
  labels:
    {{- include "translation-worker.labels" . | nindent 4 }}
data:
  NATS_URL: {{ .Values.env.natsUrl | quote }}
  NATS_STREAM: {{ .Values.env.natsStream | quote }}
  NATS_CONSUMER: {{ .Values.env.natsConsumer | quote }}
  NATS_CONSUME_SUBJECT: {{ .Values.env.natsConsumeSubject | quote }}
  NATS_RESULT_SUBJECT: {{ .Values.env.natsResultSubject | quote }}
  NATS_ERROR_SUBJECT: {{ .Values.env.natsErrorSubject | quote }}
  LIBRETRANSLATE_URL: {{ .Values.env.libretranslateUrl | quote }}
  LIBRETRANSLATE_SOURCE_LANG: {{ .Values.env.libretranslateSourceLang | quote }}
  LIBRETRANSLATE_API_KEY: {{ .Values.env.libretranslateApiKey | quote }}
