apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "report-publisher.fullname" . }}
  labels:
    {{- include "report-publisher.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.port | quote }}
  NATS_URL: {{ .Values.env.natsUrl | quote }}
  NATS_SUBJECT: {{ .Values.env.natsSubject | quote }}