apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-planner.fullname" . }}
  labels:
    {{- include "llm-planner.labels" . | nindent 4 }}
data:
  NATS_URL: {{ .Values.env.natsUrl | quote }}
  NATS_STREAM: {{ .Values.env.natsStream | quote }}
  NATS_CONSUMER: {{ .Values.env.natsConsumer | quote }}
  NATS_CONSUME_SUBJECT: {{ .Values.env.natsConsumeSubject | quote }}
  NATS_JOB_SUBJECT: {{ .Values.env.natsJobSubject | quote }}
